---
train:
  params:
    batch_size: 256
    epoch: 100
    lr: 0.001
    decay: 0.1
    decay_step: 5000
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Mnist/MPII"
    model_name: Mnist
    step: 20
  data:
    image: "/home/cyh/GazeDataset20200519/EyeBased/MPIIGaze/Image"
    label: "/home/cyh/GazeDataset20200519/EyeBased/MPIIGaze/Label"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 20
      steps: 20
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Mnist/MPII"
      model_name: Mnist
   data:
      image: "/home/cyh/GazeDataset20200519/EyeBased/MPIIGaze/Image"
      label: "/home/cyh/GazeDataset20200519/EyeBased/MPIIGaze/Label"
reader: reader_mpii
